[tool.poetry]
name = "a-flask-test"
version = "0.1.0"
description = ""
authors = ["ICRAR"]
readme = "README.md"
packages = [{include = "a_flask_test"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wallaby_hires = 'wallaby_hires.__main__:main'
